defmodule Batamanta.EscriptBuilder do
  @moduledoc """
  Builds escripts for batamanta packaging.

  This module handles the generation of escripts using `mix escript.build`
  and provides utilities for locating and validating the generated output.

  ## Usage

      escript_path = EscriptBuilder.build(config, banner_ctx)
      # Returns: "/path/to/project/_build/prod/lib/app_name/ebin/app_name"

  ## Escript vs Release

  Escripts are lightweight executables that embed the Elixir runtime
  directly, unlike releases which include the full OTP system.

  | Aspect | Escript | Release |
  |--------|---------|---------|
  | Size | ~15-30 MB | ~80-150 MB |
  | Startup | Fast | Slower |
  | Supervisor Tree | No | Yes |
  | Daemon Mode | No | Yes |
  | Hot Upgrades | No | Yes |

  Use escripts when:
  - Building CLI tools
  - Size is critical
  - No need for full OTP supervision

  Use releases when:
  - Building services
  - Need supervisor trees
  - Need distributed Erlang
  """

  alias Batamanta.Logger

  @doc """
  Builds an escript using `mix escript.build`.

  ## Parameters

  - `config` - Mix project config (from `Mix.Project.config()`)
  - `banner_ctx` - Banner context for logging

  ## Returns

  Path to the generated escript binary.

  ## Raises

  - `Mix.Error` if escript build fails
  - `Mix.Error` if escript file is not found after build
  """
  @spec build(keyword(), any()) :: Path.t()
  def build(config, banner_ctx) do
    Logger.info(banner_ctx, ">> 📦 Running mix escript.build...")

    # Ensure dependencies are compiled first
    Logger.info(banner_ctx, ">> 📦 Compiling dependencies...")

    {_out, _status} =
      System.cmd("mix", ["do", "deps.get", "--force"],
        env: [{"MIX_ENV", "prod"}],
        stderr_to_stdout: true
      )

    # Compile the project (without --warnings-as-errors to avoid false positives)
    Logger.info(banner_ctx, ">> 📦 Compiling project...")

    {compile_output, compile_status} =
      System.cmd("mix", ["compile"],
        env: [{"MIX_ENV", "prod"}],
        stderr_to_stdout: true
      )

    # Log warnings but don't fail the build unless there are actual errors
    if String.contains?(compile_output, "warning:") do
      Logger.info(banner_ctx, ">> ⚠️  Compiler warnings detected:")

      compile_output
      |> String.split("\n")
      |> Enum.filter(&String.contains?(&1, "warning:"))
      |> Enum.take(5)
      |> Enum.each(fn line -> Logger.info(banner_ctx, ">>    #{line}") end)
    end

    if compile_status != 0 do
      Logger.error(banner_ctx, "Escript build failed during compilation:")
      Logger.error(banner_ctx, compile_output)
      Mix.raise("Mix compile failed. Check output above for details.")
    end

    # Build the escript
    Logger.info(banner_ctx, ">> 📦 Building escript...")

    {output, status} =
      System.cmd("mix", ["escript.build"],
        env: [{"MIX_ENV", "prod"}],
        stderr_to_stdout: true
      )

    if status != 0 do
      Logger.error(banner_ctx, "Escript build failed:")
      Logger.error(banner_ctx, output)
      Mix.raise("Mix escript.build failed. Check output above for details.")
    end

    # Find the generated escript
    escript_path = find_escript_path(config)

    unless File.exists?(escript_path) do
      Mix.raise("Escript not found at expected path: #{escript_path}")
    end

    # Validate escript
    validate_escript!(escript_path)

    Logger.info(banner_ctx, ">> ✅ Escript built: #{escript_path}")
    escript_path
  end

  @doc """
  Finds the escript path in the build directory.

  Escripts are generated by default at:
  - `./<app_name>` (in project root, default for CLI tools)

  Or at a custom path if specified in the :escript config.
  """
  @spec find_escript_path(keyword()) :: Path.t()
  def find_escript_path(config) do
    project_root = project_root()
    app_name = config[:app]
    escript_config = config[:escript] || []

    # Check for custom path in escript config
    if custom_path = Keyword.get(escript_config, :path) do
      Path.join(project_root, custom_path)
    else
      # Standard path: in project root (mix escript.build default)
      Path.join(project_root, Atom.to_string(app_name))
    end
  end

  @doc """
  Validates that the escript is a valid executable.

  ## Checks

  1. File exists
  2. File is executable
  3. File is not empty
  4. File has shebang or is an ELF binary
  """
  @spec validate_escript!(Path.t()) :: :ok | no_return()
  def validate_escript!(escript_path) do
    unless File.exists?(escript_path) do
      Mix.raise("Escript not found: #{escript_path}")
    end

    # Check file size
    case File.stat(escript_path) do
      {:ok, %{size: size}} when size > 0 ->
        :ok

      {:ok, %{size: 0}} ->
        Mix.raise("Escript is empty: #{escript_path}")

      {:error, reason} ->
        Mix.raise("Cannot stat escript: #{reason}")
    end

    # Validate magic bytes (shebang or ELF)
    validate_magic_bytes!(escript_path)

    :ok
  end

  defp validate_magic_bytes!(escript_path) do
    case File.read(escript_path) do
      {:ok, <<0x7F, "ELF", _::binary>>} ->
        :ok

      {:ok, <<"#!", _::binary>>} ->
        :ok

      {:ok, _} ->
        Mix.raise("Escript has invalid format (not ELF or shebang): #{escript_path}")

      {:error, reason} ->
        Mix.raise("Cannot read escript: #{reason}")
    end
  end

  @doc """
  Gets the main module from escript configuration.

  Returns nil if not configured.
  """
  @spec get_main_module(keyword()) :: module() | nil
  def get_main_module(config) do
    escript_config = config[:escript] || []
    Keyword.get(escript_config, :main_module)
  end

  # Gets the project root directory
  defp project_root do
    Mix.Project.build_path()
    |> Path.dirname()
    |> Path.dirname()
  end

  @doc """
  Checks if the project has valid escript configuration.
  """
  @spec valid_config?(keyword()) :: boolean()
  def valid_config?(config) do
    escript_config = config[:escript]

    cond do
      escript_config == nil -> false
      not Keyword.has_key?(escript_config, :main_module) -> false
      true -> true
    end
  end
end
