defmodule Batamanta.EscriptBuilder do
  @moduledoc """
  Builds escripts for batamanta packaging.

  This module handles the generation of escripts using `mix escript.build`
  and provides utilities for locating and validating the generated output.

  escript_path = EscriptBuilder.build(config, banner_ctx, erts_path)


  Escripts are lightweight executables that embed the Elixir runtime
  directly, unlike releases which include the full OTP system.

  | Aspect | Escript | Release |
  |--------|---------|---------| 
  | Size | ~15-30 MB | ~80-150 MB |
  | Startup | Fast | Slower |
  | Supervisor Tree | No | Yes |
  | Daemon Mode | No | Yes |
  | Hot Upgrades | No | Yes |

  Use escripts when:
  - Building CLI tools
  - Size is critical
  - No need for full OTP supervision

  Use releases when:
  - Building services
  - Need supervisor trees
  - Need distributed Erlang
  """

  alias Batamanta.EnvCleaner
  alias Batamanta.Logger

  @doc """
  Builds an escript using `mix escript.build`.


  - `config` - Mix project config (from `Mix.Project.config()`)
  - `banner_ctx` - Banner context for logging
  - `erts_path` - Path to the ERTS that will be embedded (for build consistency)


  Path to the generated escript binary.


  - `Mix.Error` if escript build fails
  - `Mix.Error` if escript file is not found after build
  """
  @spec build(keyword(), any(), Path.t()) :: Path.t()
  def build(config, banner_ctx, erts_path) do
    Logger.info(banner_ctx, ">> 📦 Running mix escript.build...")

    # FIX: was `env: env_with_mix` (undefined). Now uses EnvCleaner.build_env/1
    # which inherits the full process env (elixir, mix, MIX_HOME etc. stay
    # available) and only overrides ERTS-related variables so `mix escript.build`
    # compiles against the exact downloaded ERTS that will be bundled, preventing
    # version mismatches at runtime when the binary is executed from a directory
    # with a different ERTS configured via asdf/mise/kerl.
    {output, status} =
      System.cmd("mix", ["escript.build"],
        env: EnvCleaner.build_env(erts_path),
        stderr_to_stdout: true
      )

    if status != 0 do
      Logger.error(banner_ctx, "Escript build failed:")
      Logger.error(banner_ctx, output)
      Mix.raise("Mix escript.build failed. Check output above for details.")
    end

    escript_path = find_escript_path(config)

    unless File.exists?(escript_path) do
      Mix.raise("Escript not found at expected path: #{escript_path}")
    end

    validate_escript!(escript_path)

    Logger.info(banner_ctx, ">> ✅ Escript built: #{escript_path}")
    escript_path
  end

  @doc """
  Finds the escript path in the build directory.

  Escripts are generated by default at:
  - `./<app_name>` (in project root, default for CLI tools)

  Or at a custom path if specified in the :escript config.
  """
  @spec find_escript_path(keyword()) :: Path.t()
  def find_escript_path(config) do
    project_root = project_root()
    app_name = config[:app]
    escript_config = config[:escript] || []

    if custom_path = Keyword.get(escript_config, :path) do
      Path.join(project_root, custom_path)
    else
      Path.join(project_root, Atom.to_string(app_name))
    end
  end

  @doc """
  Validates that the escript is a valid executable.


  1. File exists
  2. File is executable
  3. File is not empty
  4. File has shebang or is an ELF binary
  """
  @spec validate_escript!(Path.t()) :: :ok | no_return()
  def validate_escript!(escript_path) do
    unless File.exists?(escript_path) do
      Mix.raise("Escript not found: #{escript_path}")
    end

    case File.stat(escript_path) do
      {:ok, %{size: size}} when size > 0 ->
        :ok

      {:ok, %{size: 0}} ->
        Mix.raise("Escript is empty: #{escript_path}")

      {:error, reason} ->
        Mix.raise("Cannot stat escript: #{reason}")
    end

    validate_magic_bytes!(escript_path)

    :ok
  end

  defp validate_magic_bytes!(escript_path) do
    case File.read(escript_path) do
      {:ok, <<0x7F, "ELF", _::binary>>} ->
        :ok

      {:ok, <<"#!", _::binary>>} ->
        :ok

      {:ok, _} ->
        Mix.raise("Escript has invalid format (not ELF or shebang): #{escript_path}")

      {:error, reason} ->
        Mix.raise("Cannot read escript: #{reason}")
    end
  end

  @doc """
  Gets the main module from escript configuration.

  Returns nil if not configured.
  """
  @spec get_main_module(keyword()) :: module() | nil
  def get_main_module(config) do
    escript_config = config[:escript] || []
    Keyword.get(escript_config, :main_module)
  end

  defp project_root do
    Mix.Project.build_path()
    |> Path.dirname()
    |> Path.dirname()
  end

  @doc """
  Checks if the project has valid escript configuration.
  """
  @spec valid_config?(keyword()) :: boolean()
  def valid_config?(config) do
    escript_config = config[:escript]

    cond do
      escript_config == nil -> false
      not Keyword.has_key?(escript_config, :main_module) -> false
      true -> true
    end
  end
end