use anyhow::{Context, Result};
use indicatif::{ProgressBar, ProgressStyle};
use nix::unistd::execvp;
use std::{
    env,
    ffi::CString,
    fs,
    io::BufReader,
    os::unix::ffi::OsStrExt,
    path::{Path, PathBuf},
    process::ExitCode,
};
use tar::Archive;
use zstd::stream::read::Decoder as ZstdDecoder;

// GENERATED_APP_NAME, GENERATED_INSTANCE_ID, and the BEAM alive mode
// configuration come from build.rs (which reads BATAMANTA_* env vars set by
// `Batamanta.RustTemplate.compile_rust`). See RFC-0008 (rfcs/0008-beam-alive-mode.md).
include!(concat!(env!("OUT_DIR"), "/generated_config.rs"));

/// Per-binary UUID isolates runtime resources (extraction dir, future
/// socket/lock files for BEAM alive mode). Same binary → same dir on
/// repeated executions; different binaries (same payload, different build)
/// → disjoint dirs.
fn extract_dir() -> PathBuf {
    env::temp_dir().join(format!("batamanta-{}", GENERATED_INSTANCE_ID))
}

/// Path of the legacy `<app>.run` script generated by `Batamanta.RunScript`.
fn legacy_run_script_path() -> PathBuf {
    extract_dir()
        .join("release")
        .join("bin")
        .join(format!("{}.run", GENERATED_APP_NAME))
}

/// Decision for how to handle a single wrapper invocation.
#[derive(Debug, PartialEq)]
#[allow(dead_code)] // `KeeperDispatched` only constructed in Phase 4+.
enum DispatchDecision {
    /// Feature is disabled or env var unset/empty/"0" — exec the legacy
    /// `<app>.run` shell script as in pre-T-008 Batamanta.
    Legacy,
    /// Feature enabled, no keeper running (Phase 3: always the case) — warn
    /// to stderr and fall back to legacy. Real keeper dispatch in Phase 4+.
    NoKeeperAvailable(String),
    /// Feature enabled and a keeper responded. Args and stdin forwarded,
    /// exit code captured. (Phase 4+)
    KeeperDispatched,
}

/// Read the per-binary env var (`GENERATED_BEAM_ALIVE_VAR`) and decide.
fn resolve_dispatch() -> DispatchDecision {
    if !GENERATED_BEAM_ALIVE_ENABLED {
        return DispatchDecision::Legacy;
    }

    let var_name = GENERATED_BEAM_ALIVE_VAR;
    let raw = env::var(var_name).unwrap_or_default();
    let trimmed = raw.trim();

    if trimmed.is_empty() {
        // Env var unset/empty → use baked default_ms.
        if GENERATED_BEAM_ALIVE_DEFAULT_MS > 0 {
            // The default kicks in. Phase 3 has no keeper yet.
            return DispatchDecision::NoKeeperAvailable(format!(
                "default TTL {}ms requested but no keeper running",
                GENERATED_BEAM_ALIVE_DEFAULT_MS
            ));
        } else {
            return DispatchDecision::Legacy;
        }
    }

    if trimmed == "0" {
        return DispatchDecision::Legacy;
    }

    match trimmed.parse::<u64>() {
        Ok(0) => DispatchDecision::Legacy,
        Ok(ms) => {
            // Validate range (24h cap consistent with the Elixir validator).
            if ms > 86_400_000 {
                DispatchDecision::NoKeeperAvailable(format!(
                    "TTL {}ms exceeds 24h cap (86400000ms)",
                    ms
                ))
            } else {
                DispatchDecision::NoKeeperAvailable(format!(
                    "TTL {}ms requested but no keeper running",
                    ms
                ))
            }
        }
        Err(_) => DispatchDecision::NoKeeperAvailable(format!(
            "env var {:?} is not a valid integer: {:?}",
            var_name, raw
        )),
    }
}

/// Try alive mode dispatch. Phase 3 stub: connect to the Unix socket and
/// fail because no keeper exists yet. Phase 4+ replaces this with real
/// IPC protocol implementation.
#[allow(dead_code)] // Phase 4+ dispatcher will use this.
fn try_alive_dispatch(_ttl_ms: u64) -> Result<(), String> {
    let sock_path = extract_dir().join("keeper.sock");
    match std::os::unix::net::UnixStream::connect(&sock_path) {
        Ok(_) => unreachable!("Phase 3: no keeper exists yet, connect should fail"),
        Err(e) => Err(format!(
            "keeper socket not found at {}: {}",
            sock_path.display(),
            e
        )),
    }
}

/// Extract payload if not already extracted (same per-binary dir).
fn extract_payload_if_needed(extract_dir: &Path, bytes: &[u8]) -> Result<()> {
    if extract_dir.exists() {
        return Ok(());
    }

    let spinner = ProgressBar::new_spinner();
    spinner.set_style(
        ProgressStyle::default_spinner()
            .template("{spinner:.green} {msg}")
            .unwrap(),
    );
    spinner.set_message("Extracting payload...");

    fs::create_dir_all(extract_dir).context("Failed to create temp dir")?;
    let cursor = std::io::Cursor::new(bytes);
    let decoder = ZstdDecoder::new(cursor).context("Invalid zstd payload")?;
    let mut archive = Archive::new(BufReader::new(decoder));
    archive
        .unpack(extract_dir)
        .context("Failed to unpack payload")?;

    spinner.finish_and_clear();
    Ok(())
}

/// Build argv for the child process from `args`.
fn build_argv_for(program: &Path, args: &[String]) -> Result<Vec<CString>> {
    let program_cstr = CString::new(program.as_os_str().as_bytes())
        .context("Invalid program path")?;
    let mut argv = vec![program_cstr];
    for arg in args {
        argv.push(CString::new(arg.as_bytes()).context("Invalid arg")?);
    }
    Ok(argv)
}

/// Legacy single-shot: replace this process with the `<app>.run` script.
fn exec_legacy(run_script: &Path, args: &[String]) -> Result<()> {
    let argv = build_argv_for(run_script, args)?;
    let program = &argv[0];
    let _ = execvp(program, &argv);
    Err(anyhow::anyhow!(
        "execvp failed: {}",
        std::io::Error::last_os_error()
    ))
}

fn main() -> Result<ExitCode> {
    let bytes = include_bytes!(concat!(env!("OUT_DIR"), "/payload.tar.zst"));
    let extract_dir = extract_dir();
    extract_payload_if_needed(&extract_dir, bytes)?;

    let run_script = legacy_run_script_path();
    if !run_script.exists() {
        anyhow::bail!(
            ".run script not found at {}. \
             Expected GENERATED_APP_NAME={}",
            run_script.display(),
            GENERATED_APP_NAME
        );
    }

    // Collect args (skip argv[0] = wrapper path).
    let args: Vec<String> = env::args().skip(1).collect();

    match resolve_dispatch() {
        DispatchDecision::Legacy => {
            exec_legacy(&run_script, &args)?;
            // exec_legacy only returns Err (execvp replaced the process or failed).
            Ok(ExitCode::from(1))
        }
        DispatchDecision::NoKeeperAvailable(reason) => {
            eprintln!(
                "batamanta: BEAM alive mode requested ({reason}); \
                 falling back to legacy single-shot."
            );
            exec_legacy(&run_script, &args)?;
            Ok(ExitCode::from(1))
        }
        DispatchDecision::KeeperDispatched => {
            // Phase 4+ will reach here. For now unreachable.
            eprintln!("batamanta: keeper dispatched (Phase 4+)");
            Ok(ExitCode::from(0))
        }
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_app_name_is_compiled() {
        let app = GENERATED_APP_NAME;
        assert!(!app.is_empty());
    }

    #[test]
    fn test_instance_id_is_compiled_and_is_uuid() {
        let id = GENERATED_INSTANCE_ID;
        assert!(!id.is_empty(), "INSTANCE_ID must be baked at build time");
        assert!(
            uuid::Uuid::parse_str(id).is_ok(),
            "INSTANCE_ID must parse as UUID v4, got: {}",
            id
        );
    }

    #[test]
    fn test_extract_dir_uses_instance_id() {
        let dir = extract_dir();
        let path_str = dir.to_string_lossy();
        assert!(path_str.contains(GENERATED_INSTANCE_ID));
        assert!(path_str.starts_with("/tmp/"));
        assert!(path_str.contains("batamanta-"));
    }

    #[test]
    fn test_payload_exists() {
        let bytes = include_bytes!(concat!(env!("OUT_DIR"), "/payload.tar.zst"));
        assert!(bytes.len() > 100, "Payload seems too small");
    }

    // ------------------------------------------------------------------
    // resolve_dispatch/0 — needs to be tested by mocking env vars at runtime.
    // We test the pieces separately using a unit-level approach.
    // ------------------------------------------------------------------

    #[test]
    fn test_resolve_dispatch_legacy_when_env_var_unset() {
        // Without env vars set, resolve_dispatch returns Legacy (no env var
        // means no alive-mode request — feature defaults to off).
        // Note: this test depends on the test environment not having the
        // per-binary env var set. In CI, that's true.
        // SAFETY: env::remove_var is unsafe in recent Rust; skip if needed.
        let var = GENERATED_BEAM_ALIVE_VAR;
        let saved = env::var(var).ok();
        env::remove_var(var);

        let decision = resolve_dispatch();
        // Could be either Legacy (default_ms==0) or NoKeeperAvailable
        // (default_ms>0). Both are valid "not legacy fallback" outcomes.
        // Just verify it's not KeeperDispatched (impossible in Phase 3).
        assert_ne!(decision, DispatchDecision::KeeperDispatched);

        if let Some(v) = saved {
            env::set_var(var, v);
        }
    }
}
